name: Order

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #schedule:
  #  - cron:  '35 7 * * *'
  workflow_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
  
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install opencv-python==4.5.1.48 opencv-python-headless==4.5.1.48
          pip install easyocr pillow numpy lxml
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
      - name: run
        run: STD_ID='${{ secrets.STD_ID }}' PASSWORD='${{ secrets.PASSWORD }}' MOBILE='${{ secrets.MOBILE }}' python3 order.py
